#+DATE: 2019-06-05T10:09:06+02:00
#+TITLE: Curriculum Vitæ
#+DRAFT: true
#+TYPE: cv

** Work Experience
*** Absa (formerly Barclays Africa)
|-------------------------+----------------------------|
| February 2016 - present | Johannesburg, South Africa |
|-------------------------+----------------------------|
|                         | Creative Technologist      |
|-------------------------+----------------------------|

- Initially given a crisis portfolio, but was able to turn it around into a success story for the platform.
- Introduced the company to React & helped to integrate React into Adobe Experience Manager before there was native support.
- Consistently given & delivered high risk or technical briefs considered too risky for other teams or members.
- Repeatedly asked to assist projects in crisis with a great record of delivering core requirements on time.
- Responsible for projects from concept through to deployment across Africa.
- Motivated for & established the company's first virtual reality capability across three cities.
- Established a partnership with a University to better explore virtual reality & its capabilities.
- Collaboratively explored new forms of user engagement using virtual & augmented reality.
- Provided a number of proof of concept projects using virtual & augmented reality.
- Contributed to a multi-disciplinary team on the practical application of the new corporate brand.
- Helped establish work flows & pipelines for different portfolios.
- Established best practises & supported development teams in their tasks.

*** McCann Johannesburg
|------------------------------+-----------------------|
| January 2015 - December 2015 | Sandton, South Africa |
|------------------------------+-----------------------|
|                              | Senior Developer      |
|------------------------------+-----------------------|

- Only developer in the newly created digital department.
- Conceptualised, successfully motivated, built & deployed a cross-device, cross-platform, mobile based augmented reality solution.
- Interfaced directly with clients to unpack & define their core objectives.
- Supported the project managers, community managers & designers in the execution of their tasks.
- Provided scopes of work, functional specifications as well as process pipelines for projects.
- Single-handedly build, deployed & maintained many of the projects I was involved with.
- Successfully deployed projects within the tight time & budget constraints of an agency.
- Provided technical direction & insights into numerous technologies & tech-stacks.
- Clients include: McCann <span>Nestle</span> <span>Waltons</span> <span>Kauai</span> <span>UIP</span> <span>Chevrolet</span> <span>Isuzu</span> <span>Zurich</span> <span>Econet</span>

*** Freelance
|------------------------------+------------------------|
| January 2014 - December 2014 | Pretoria, South Africa |
|------------------------------+------------------------|
|                              | Multi-media Developer  |
|------------------------------+------------------------|

- Assisted clients to narrow down & define their core objectives.
- Provided technical direction on key technologies & realistic timelines required to achieve objectives.
- Successfully conceptualised, scoped, developed & deployed a number of projects.
- Utilised time to expand knowledge base, streamline development processes & investigate interesting technologies.

*** Gloo
|---------------------------+-------------------------|
| June 2012 - December 2013 | Greenside, South Africa |
|---------------------------+-------------------------|
|                           | Senior Developer        |
|---------------------------+-------------------------|

- Responsible for taking high-pressure individual & team briefs from concept through to deployment.
- Successfully & consistently deployed projects within the given time-lines & budgets.
- Called in to assist with crisis or time-critical projects, as well as difficult clients.
- Able to identify process bottle-necks or pain-points & possible ways to mitigate or solve these issues.
- Provided technical direction for technologies not in the company portfolio.
- Supported & up-skilled the junior developers & creatives.
- Clients include: BMW <span>FNB</span> <span>MINI</span> <span>RMB</span> <span>Samsung</span> <span>SA Tourism</span>

*** LXi
|------------------------------+------------------------|
| January 2011 - February 2012 | Randburg, South Africa |
|------------------------------+------------------------|
|                              | Developer              |
|------------------------------+------------------------|

- Only developer in the company.
- Reverse engineered application development for existing & new devices.
- Successfully planned, developed & deployed touch, multi-touch and motion capture applications.
- Researched & implemented technologies for the company.
- Interfaced directly with clients to unpack & better understand their core requirements & objectives.
- Clients included: Paragon Group <span>PWC</span> <span>Sanofi Aventis</span> <span>SAP</span>

*** iLogic
|--------------------------+-----------------------|
| May 2010 - November 2010 | Sandton, South Africa |
|--------------------------+-----------------------|
|                          | Flash & Web Developer |
|--------------------------+-----------------------|

- Responsible for taking high-pressure briefs from concept through to deployment.
- Successfully planned, developed & deployed projects on desktop, social media & web.
- Deadline driven, consistently delivered projects in the given timelines.

*** ILA Vietnam
|------------------------+-----------------|
| July 2007 - March 2009 | Hanoi, Vietnam  |
|------------------------+-----------------|
|                        | English Teacher |
|------------------------+-----------------|

- Provided IELTS preparation, as well as custom classes for business & educational English.
- Commended on my innovative teaching style, vibrancy of my classes & the variety of media used in my lessons.
- Worked with various PC based learning packages with my students & helped evaluate the effectiveness of these resources.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed teaching resources and presented workshops to my peers around the topics: “Film & video in the classroom” <span>“Interactive software in an educational setting”.</span>

*** Aston Schools
|--------------------------+---------------------------|
| August 2006 - March 2007 | Zhengzhou, China          |
|--------------------------+---------------------------|
|                          | Foreign Manager & Teacher |
|--------------------------+---------------------------|

- Co-managed a school of 200 students, 2 foreign teachers, 2 Chinese teachers & a number of Chinese staff.
- Responsible for orientation, development & continuous assessment of the teaching skills of the foreign teachers.
- Developed teaching schedules & provided spread sheet templates for payrolls.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Planned and delivered promotional activities for the school including: curriculum development <span>designing advertisements</span> <span>delivering promotional classes (all ages)</span> <span>promotional field work</span> <span>judging English competitions</span> <span>creating public English corners.</span>

*** Aston Schools
|------------------------+----------------|
| April 2005 - July 2006 | Jinan, China   |
|------------------------+----------------|
|                        | Senior Teacher |
|------------------------+----------------|

- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed school resources including: flash-cards <span>posters</span> <span>authentic materials.</span>

** Other Initiatives
*** [[https://www.afrikaburn.com/][AfrikaBurn]]
- *2019:* Project lead for the 'Sweet Love Gateway' art work.
- Successfully proposed the project & motivated for grants.
- Planned, prototyped, budgeted & successfully executed the project.
- Oversaw & co-ordinated the transportation of equipment to the build site.
- Solely responsible for the lighting of the project, which was made up of 40m/ 2400 individually addressable LED lights.

- *2010:* Assisted with the development of the original website theme.

*** OppiKoppi
- Successfully conceptualised, motivated for, prototyped & led/ co-led the construction of a number of structures.
- Part of the core team which co-ordinated efforts between participants.
- Responsible for sourcing & transporting the equipment.

- *2017:* Assisted with the construction of the final tower.
- *2015:* Led the construction of the tower & assisted with the construction of the catapult.
- *2014:* Led the construction of the tower & assisted with the construction of the shade dome.
- *2013:* Led the construction of the solo tower.
- *2012:* Led the construction of the medic tower & assisted with the construction of the primary tower.
- *2011:* Led the construction of the newer, bigger tower.
- *2010:* Led the construction of the first tower.

** Education
*** [[https://www.coursera.org/account/accomplishments/specialization/3VS6JECTTJKS][Coursera Specialisation: Functional Programming in Scala]]
|---------------------------+------------------------------------------|
| November 2016 - July 2017 | Pretoria, South Africa                   |
|---------------------------+------------------------------------------|
|                           | École Polytechnique Fédérale de Lausanne |
|---------------------------+------------------------------------------|

- stuffs

*** CELTA
|-------------------------------+----------------------|
| September 2006 - October 2006 | Ho Chi Minh, Vietnam |
|-------------------------------+----------------------|
|                               | Cambridge University |
|-------------------------------+----------------------|

- 

*** Bachelor Information Science (Multimedia)
|------------------------------+------------------------|
| January 2001 - December 2004 | Pretoria, South Africa |
|------------------------------+------------------------|
|                              | University of Pretoria |
|------------------------------+------------------------|

Major in Multimedia
- Concerned with the effective use of media types within a computer science context via the Internet, PCs or hand-held devices.
- Developed school resources including: flash-cards <span>posters</span> <span>authentic materials.</span>

Major in Computer Science
- Concerned with computer operation and software development.
- Major skills include: object orientated programming (focused around C++ and Java); design patterns; data structures; networks.

Major in English
- Completed an additional major in English.

