#+DATE: 2018-02-10T16:42:43+02:00
#+TITLE: The Almighty Prototype
#+DRAFT: true

<img style="width:180px; height:180px; float:right;" src="../../img/react.svg" alt="React"/>
Hindsight is completely unforgiving. Being able to look back and observe oversights or pitfalls is a luxury that most projects & individuals cannot afford. This is why you need to make space for yourself to fail, and fail enough to learn the lesson. Because, in all honesty, failure is the best teacher that we have, we just need to choose a suitable time to fail. And that time is usually in the early stages of a project when it is still 'relatively' easy to accommodate changes.

** But I know what the user wants
   Stakeholders or clients often do not see the true value of prototyping. Why budget time refining at the very beginning of the project? And it is a valid point, since the 'agile approach' expects us to deploy a 'minimum viable product' (MVP) as soon as possible and iterate on it. In the panic to get to market, it is very easy to overlook the word 'viable' in MVP.

   Prototyping & user testing at an early stage will provide a solid foundation to iterate upon. A few unfortunate projects I have been involved with were driven by stakeholders who were convinced that they knew their users. When the project launched and did not get the traction they had hoped for, they immediately blamed the designers & developers. A closer look at the analytics for the product, as well as extensive user testing, showed that the stakeholders did not understand their users as well as they claimed. Hindsight prooved that simple changes early in the project may have altered the uptake dramatically. But making those changes essentailly required a rework of the bulk project.

** The need for speed
   Talk is cheap. Most stakeholders are what I refer to as, "obsessively compulsively indecisive". That is, /they do not know what they want, but they know that they want it now/.

   

** Hi vs Lo fidelity

** Multi-purpose
   A prototype can achieve a number of goals

** Tools
