#+DATE: 2018-11-04T16:42:43+02:00
#+TITLE: The Almighty Prototype
#+DRAFT: true

<img style="width:180px; height:180px; float:right;" src="../../img/react.svg" alt="React"/>
Hindsight is completely unforgiving. Looking back & observing oversights is a luxury that most projects cannot afford. This is why you need to make space for yourself to fail, and fail enough to learn the lesson. Because, in all honesty, failure is the best teacher that we have, provided we choose a suitable time to fail. And that time is in the early stages of a project when it is still 'relatively' easy to accommodate changes.

** But I know what the user wants
   Stakeholders or clients often do not see the true value of prototyping. Why budget time refining at the very beginning of the project? The 'agile approach' expects us to deploy a 'minimum viable product' (MVP) as soon as possible & then iterate on it. In the panic to get to market, it is very easy to overlook the word 'viable' in MVP.

   Prototyping & user testing at an early stage will provide a solid, iterable foundation. I have been involved with projects where the stakeholders were convinced that they knew their users. When the project launched and did not get the traction hoped for, the focus shifted to the designers & developers.

We took a closer look at the analytics and conducted some user testing. The data showed that the stakeholders did not understand their users as well as they claimed. 
   
** Hi vs Lo fidelity
   The choice of making a quick & dirty user flow using paper, or a graphically richer representation including screen transitions & working components, depends on the stage of the project.

** Multi-purpose
   The ability to rapidly & effectively prototype can provide different results or insights, depending on how you use the prototype. The specific prototype's fidelity comes into play here, but some general uses include:

   - Provide a concrete example to an abstract concept.

** Talk is cheap
   Many stakeholders are, "obsessively compulsively indecisive". Or in other words, "they do not know what they want, but they know that they want it now".

   One clear example of this was when a stakeholder insisted that we had everything we needed to start development. To show the stakeholder some of the pitfalls of their 'signed off' & 'approved' project, we rapidly prototyped some of the screens they had given us using [[https://framer.com/][Framer]]. When we sent the stakeholder a preview link of the framer prototype, an amazing thing happened, they sent back a detailed critique of the prototype questioning design choices, user flows as well as various user experience (UX) components. When we challenged this critique, showing the stakeholder that we had merely mocked up the very same designs they had given us, the stakeholder calmed down and allowed us some room to refine the product.

** Tools
