#+DATE: 2017-09-01T13:32:22+02:00
#+TITLE: Do you even functional bro?
#+DRAFT: true

My interest grew from a side conversation I over-heard. After that, every taste taught me something different. There is something truly haunting about functional programming.

I have completed [[https://www.coursera.org/account/accomplishments/specialization/3VS6JECTTJKS][Functional Programming in Scala]] via [[https://www.coursera.org][Coursera]]. I was not fully prepared for the learning curve as many of the concepts and principles were new to me. What I took away from the course has had a real impact on the way I approach software development.

*** The discussion
Of course there is debate, we are spoiled for choice. There are three classic schools: imperative, procedural & functional. They all have their strengths. I have used imperative more than procedural. So when tasked with converting your general approach and thoughts regarding programming, a lot depends on the context. Concession make sense as stated by in [[Https:https://medium.com/@bfil/just-enough-functional-programming-a0c4fd09c8f7][Just enough functional programming]].

You then also get the other view in [[https://www.vincit.fi/en/blog/empty-promises-and-other-heresy/][Empty promises and heresy]]. My journey started with Scala though my curiosity was captured by [[https://clojure.org/][Clojure]]. Being fully emerged in a functional environment enables deeper insights but needs to be part of your daily life. At the time, I had yet to integrate a fully functional approach into my daily tasks.

*** Is that you JS?
My first love was [[https://en.wikipedia.org/wiki/ActionScript][ActionScript]]. I still miss features of the language, as you would an old friend. There was even a time I used ActionScript & JavaScript in tandem, the two [[https://en.wikipedia.org/wiki/ECMAScript][ECMAScript]] twins. I hurt when they fought and I was sad to see ActionScript leave... I resented JavaScript. This changed with time as I learned that it was not JavaScript that I was resenting but rather the contemporary practises. In time, I witnessed JavaScript adapt and morph into what we see today.

In many ways, I am grateful that the web has iterated so rapidly enabling an environment for [[https://facebook.github.io/react/][React]]. I felt joy when I realised 'how' React was solving many of my more common struggles. 
