#+DATE: 2017-06-19T07:37:40+02:00
#+TITLE: The Joys of Craft
#+DRAFT: false
#+TYPE: post

I get great satisfaction from viewing a product I built using tools I prefer following principles I believe in. 

On any given day, I work on a number of tech stacks that get the job done but leave me thinking, "If I could have built this from scratch?" Most projects suffer from budget & time constraints and end up being good enough. But when you do have enough time, when you are able to pick your tools and set them up just right and you watch them work together... then the endorphin's flow. 

To be clear, I am not saying that one technology is better than another (enter 'ninja vs pirates', 'spaces vs tabs'). Each developer's preferences are as unique as they are. Nor am I saying that any slice of coding Nirvana will survive code debt or entropy. Code cannot be perfect (not according to [[https://plato.stanford.edu/entries/goedel-incompleteness/][Gödel's incompleteness theorem]]) and code can always be improved or expanded. 

My point is when you have full control of your environment and tools, your motivation should increase which results in a better end product.

Blogs and the CMS's that power them are diverse in their approaches. They all have their strengths and fulfill particular needs. My desires for this blog were:

- as much freedom on the front-end as possible.
- less dependence on a back-end (mostly because I am the only contributor).
- support for task runners.
- able to author using an editor of my choice.

** Obsessively Compulsively Indecisive
     So why even bother building your own blog? There are such great mediums out there like... erm... [[https://medium.com/][Medium.com]]. They provide greater content discovery and more tools & features so that you can focus on writing. 

     Content is a large part of blogging, but I want to tweak the presentation too. I plan to play with the layout, to try new things and see what doesn't work. If I iterate over a number of bad ideas, maybe I will discover a good. 

     - Should the focus always be center aligned?
     - Can I solve most navigation & presentation issues with JS disabled?
     - +Susy+ CSS grid & flexbox provides such flexibility with layouts, why not experiment? 
     - What will an odd number of columns in the grid do to the balance?
     - Can the balance be corrected using other visual techniques?

To sate my own curiosity, the layout on this site may change from time to time.
