#+DATE: 2017-06-18T13:49:02+02:00
#+TITLE: We're Live!
#+DRAFT: false

To say that this has been a long time coming would be an understatement, but I am very please to be at this point. There has been so much that I have wanted to post that completing the blog redesign & redevelopment has been a priority. But before I jump into topics of interest, I just wanted to list some of the technologies that are driving the blog.

**** Hugo
     The more I have used [[https://gohugo.io/][Hugo]], the more I have grown to love it. My first attempts at a blog used a CMS that was database driven, which made sense at the time and is still very relevant for large, distributed teams. But the need to store your content in a database in addition to hosting costs made less sense with the rise of [[https://www.staticgen.com/][static site generators]]. It is a diverse field, with a generator suited to everyone's particular coding tastes but once Hugo started supporting [[http://orgmode.org/][org-mode]] for content, that was when I was truly hooked.

     Another thing that I love about Hugo is the fact that you can customise it to your tastes. It handles the content but then quickly gets out of the way so that you can bring in other tools or packages. It is fast, stable and provides all the functionality that I need or want. I only have praise for the team, Hugo is a joy to work with.

**** GitHub & GitHub Pages
     Like most developers, I rely heavily on version control. Even though most of the work I do goes into private repositories, I am starting to consolidate my work in [[https://github.com/][GitHub]]. For this blog specifically, I am using [[https://pages.github.com/][GitHub Pages]] for hosting. If there is no major reliance on a back end (in this case, there isn't) then it makes a lot of sense.

**** Cloadflare
     So you have a static website but you now need a SSL certificate or simple server functionality? Enter [[https://www.cloudflare.com/][Cloudflare]], helping secure your website as well as many additional benefits. Honestly, I have not played around enough with Cloudflare to fully understand all of its benefits but it did solve a few issues I was having, and it solved it for free. Thanks Cloudflare!

**** Gulp
     Task runners is another crowded field but I have grown very found of [[http://gulpjs.com/][Gulp]]. As time goes by, I may simplify my builds using more generic tools (i.e. using [[https://www.npmjs.com/][npm]] natively or bash scripts) but Gulp does what I need it too and it does it well.

**** Susy
     For the life of me, I cannot understand why [[http://susy.oddbird.net/][Susy]] has not been more widely adopted. I have been using Susy as a [[http://sass-lang.com/][Sass]] grid system for a few years now and the flexibility it gives me and my layouts is unmatched. We are now seeing the rise of flex-box and CSS-grid (which will probably replace Susy, eventually), but Susy has allowed me as a developer to, hilariously, break out of the grid system paradigm. It has also allowed the designers I have worked with greater freedom but not at the expense of my sanity or weekends.

**** Emacs
     My love of [[https://www.gnu.org/software/emacs/][Emacs]] grows daily (cue all competing IDE fan-boys & trolls). After a number of years using it primarily as a time-tracking or scoping tool, I recently took the plunge and started doing all my development in it and, well, my quality of life has increased significantly.

Is it the only IDE solution & does it do everything better than all the others?

No, but what it can do and once you get over the learning curve & play to its strengths, you see the reasons why there are so many Emacs fanatics out there. Tip 22 from the [[https://pragprog.com/book/tpp/the-pragmatic-programmer][Pragmatic Programmer]] was 'Use a single editor well'. This struck me as odd at the time because I was using a number of them simultaneously. Each one had its specific thing that it did well but fell short in other respects. Only now do I see the advantage of consolidating most of my working life in editor. This does not mean that I do not use other IDE's when I do not have a choice (I am looking at you [[https://www.visualstudio.com/][Visual Studio]] & [[https://developer.apple.com/xcode/][Xcode]]) but Emacs feels like home every time I fire it up.

**** JavaScript
     Or lack thereof. One of the goals for the blog was to see if I could solve most problems without having to use JavaScript. [[https://stallman.org/][Richard Stallman]] and his approaches to software development have certainly started to impact my views, even if it is inconvenient. It is not possible for me to produce completely 'free' software at this stage but that does not mean it is not an ideal worth striving toward. The blog does run Analytics but should still work if the user decided to browse with JavaScript disabled. Again, not a day goes by when I do not write some JavaScript and I am enjoying my adventures into the functional side of the language, but this blog is as much about experimenting & prototyping as it is about blogging.

