#+DATE: 2019-07-30T02:22:22+02:00
#+TITLE: Sweet Love Gateway
#+DRAFT: false
#+TYPE: post

{{< img name="night_1.jpg" classes="right corners" alt="Description for screen readers." >}}
Ephemeropolis was my first burn. I got involved with the AfrikaBurn website build in 2010 but I never attended. It had long been on the to-do list, so we started making plans late 2018. The core build team included [[https://www.facebook.com/igor.zeljko.77][Igor]], [[https://www.facebook.com/alastair.mehl][Alastair]], [[https://www.facebook.com/magoshashot][Margaret]], [[https://www.facebook.com/tiffanychi101][Tiffany]] and myself. Supporting the team was [[https://www.facebook.com/CyBeRmAnZA][Bjorn]] as well as the 'NoFomosapiens', who were all incredible. Oppikoppi and Meilie-pop had bigger build teams but many members couldn't attend AfrikaBurn. Contributing to AfrikaBurn seemed natural since we had built structures at festivals before.{{< break >}}The project took the form of a [[https://www.mathcurve.com/surfaces.gb/paraboloidhyperbolic/paraboloidhyperbolic.shtml][hyperbolic paraboloid]] gateway (look at my fancy vocabulary). Igor, Alastair and Margaret had built this structure before at Oppikoppi. Based off of their insights, I thought there was room to refine 'how' it was build. I also took on the responsibility of lighting the structure.

** The Problem Statement
   The structure itself looks simple enough. A square comprised of four square lashings at each corner. The hyperbolic paraboloid is created when you warp the 2D square into a 3D space. There is an interesting by-product of the shape: the surface or mesh bends to accommodate the frame, but the individual threads remain straight. Some of the first problems to solve were:

   - How to secure the individual threads to the poles?
   - What is the optimal spacing between the threads to create a dense enough weave to catch the LED light?
   - Possible ways to achieve the above without over working the build team?

   The first few times the structure was built, there was a lot of spacing between the threads. Too much to catch the light. The threads where also tied to the poles individually, which made weaving labour intensive. First, each thread needed to be tied into place. When the structure was hoisted into its final position, each thread need to be tightened. Unsurprisingly, the team agreed that there was room to improve here.

   My programming self needed a way to speed up the anchoring and weaving. There had to be a way to 'for loop' / 'while loop' / 'map' over the threads.

*** Prototyping
    {{< img name="prototype.jpg" classes="left corners" alt="Description for screen readers." >}}
    This is one of those skills that matures like a fine wine. When I was younger, brute force and enthusiasm would carry me through most projects. With time, I realised that I was making similar mistakes at similar stages of a project. Worse, avoidable mistakes were made because all stakeholders were not consulted. The process of finding and fixing issues doesn't go away, it's 'when' you fix them that prototyping can help with.{{< break >}} Prototyping for pioneering projects was always a given. As a scout (aka young hot-shot who builds first and explains later, dealing with and fixing issues as they arise), prototyping was what the scout master told you to do. This resulted in a small version of the real version, which was great for photo opportunities (small version in foreground, big version in background). We did attempt to measure and prototype to scale, but the true value of prototyping was lost to us.{{< break >}} As I have mentioned in a [[https://chrispyke.com/post/almighty-prototype/][previous post]], prototypes are my sandbox. It's a space where I can play and make mistakes before they result in serious consequences. 

*** Iteration
    We set about trying different approaches. The first prototype was concerned with the basic shape.
 
    - Could the hyperbolic paraboloid be hoisted into position from a flat 2D square? 
    - Would the shape appear if we had two flat, perpendicular surfaces that weren't woven into one another? 

    As much as a small scale prototype could, it confirmed the above was possible. The structure would not be as secure as if the two surfaces were woven into one another. But the time spent weaving would be reduced. It would also allow us to tighten threads without them getting caught in the weave. There were obvious problems with the first prototype, but it served its purpose and was super quick to make.

    The next few problems focused on threading and weaving. Prototype two and three would help solve the following:

    - Could we anchor the threads on the poles so that we could weave and tighten multiple threads simultaneously?
    - Was there a possibility of weaving more than a single, long thread at a time?
    - Could we access the anchor points from the ground, once the structure was getting close to its final shape?

    {{< img name="prototype_2.jpg" classes="right corners" alt="Description for screen readers." >}}
    We started investigating different types of thread anchors. What was the cost of an anchor and how long would it take to secure it to a pole? {{< break >}} One solution proposed by Igor or Tiffany (or both) was to use metal chains. If the chain was secured onto the pole, it provided a ton of anchor points. This was better than hooks or eye-hole bolts which needed to be secured individually. It wasn't perfect but it did provide the best 'number of anchor points per cost' ratio.

    The actual method of weaving the thread through the chains was the next issue. After an afternoon of weaving, prototype two proved that simply feeding the thread through the chain was not good enough. It was impractical because of the volume of threads as well as the confusion caused by different weaving styles. Igor suggested a different approach, feeding the incoming end of the thread through a single chain link, running the thread along the chain and then feeding the out-going end through a link further along. This made tightening threads clearer as it was immediately evident which thread needed pulling vs feeding. Again, there is a programmatic term for this: clear and descriptive variable names.

    With these two pivotal issues solved in theory, I focused on some of the finer construction details. The surface area of the hyperbolic paraboloid is smaller than a flat square. If we could get the starting frame closer to the final shape, we could reduce the amount of wasted thread. This meant hoisting two corners up on barrels at the very start, as well as moving in the base poles. Additionally, we didn't need access to all the anchor points while tightening the weave, only half of them. In theory, we could keep one half of the structure on the ground and hoist the other. We could do this iteratively and shouldn't need extra scaffolding to secure the structure in the air.

    Armed with these insights, I felt confident that we could erect the structure on the day.

*** Individually Addressable Awesomeness
    I had an idea of 'how' I wanted to illuminate the structure, but I was exploring new ground. It culminated into my first adventure into micro-controllers. I was wholly unprepared for the end result. 

   {{< img name="night_3.jpg" classes="center corners" alt="Description for screen readers." >}}
    It started with crawling the internet, inspecting tutorials, looking at specs, looking at prices, then re-looking at specs and prices. I tried to factor redundancy into the system. Often, I would restart the process when I found more promising solutions.

    The first problem was power. After checking availability and cost, we settled on a battery of car batteries. Bjorn was able to source the car batteries and some solar panels to charge them. At the time, we were unsure how much power the whole system would use? So Bjorn got five car batteries to be safe.

    As for the LEDs, I was able to source some WS2813 strips (upgraded WS2812b). They were each 5 meters long, with 60 LEDs per meter. Each strip had 300 individually addressable LEDs. This had a potential power draw of 90W per strip (if each LED was burning white light at full brightness). The structure comprised of four 11 meter poles, so we had roughly 40 meters that we needed to cover with LEDs. That is 2400 individually addressable LEDs... I was starting to get very excited.

    {{< img name="day_1.jpg" classes="right corners" alt="Description for screen readers." >}}
    The LED strips ran on 5v, which was handy. We needed step-down converters to get from 20v to 5v to run the strips and micro-controllers. I was able to get an idea of the processing power required for that number of LEDs from [[https://github.com/FastLED/FastLED/issues/288][this thread]]. To ensure that I wasn't overworking the controllers, I decided to dedicate an Arduino DUE to each pole.{{< break >}} The next issue was interaction. I sourced two lasers that produced line beams and 6 photo-resistors to produce a 'trip wire' system. I then setup a Raspberry Pi 3b to receive signals from the photo-resistors. The Rasberry Pi also co-ordinate lighting effects with the Arduinos. As I worked on the system, I realised communication could be simplified by favoring WIFI over cabling. I replaced the Arduino Duos with ESP32 controllers. Communication was further streamlined using the [[http://mqtt.org/][MQTT protocol]]. The theory was sound and I got a working version running in my garage.

    Time caught up with me in the end. I did as many general tests as I could before packing up the system and preparing for the trip to Tankwa Town.

*** Show Time

    /"No plan survives first contact with the enemy,"/ said [[https://en.wikiquote.org/wiki/Helmuth_von_Moltke_the_Elder][Helmuth von Moltke the Elder]].

    {{< img name="day_2.jpg" classes="left corners" alt="Description for screen readers." >}}
    The group that I was traveling with needed two full days to get from Johannesburg to Tankwa. We were venturing into the unknown (i.e. none of us had been to AfrikaBurn before), so there was a fair amount of over-preparation.{{< break >}} The first hurdle was separating the essential equipment from the 'nice to haves'. The second was to get everyone into cars and moving. One of the cars blew a tyre on the nice highway. We hadn't even started driving on the tyre-shredding gravel roads yet. We dealt with all of this in turn, trying to balance the group's feelings with the common objectives.{{< break >}} After we got to Tankwa town and setup our tents, we went in search of our 11 meter poles. We found them stacked by the Clan's Lamp (the core AfrikaBurn structure). The Clan helped us purchase and transported the poles to Tankwa town. This greatly simplified our lives and we were very grateful to the Clan for their support. After locating the poles, we left transporting them to the build site for the next morning.

    Three of the 11 meter poles were missing when we woke up. Everyone, including the organisers, were stunned. Search parties were sent out, calls were made and the whole camp started looking for the missing poles. Igor eventually spotted them at another project. We got help transporting them to our build site and then started construction. The team's moral took a hit.

    When we started fastening the chains to the poles, one of the poles snapped. There were many possible reasons why the pole could have snapped (the wood was untreated by choice, the poles were left out in the desert for too long, rough treatment by the pole thieves). But none of this helped solve the problem.

    We had two options before us: try to brace the broken pole with metal (causing further delays) or literal cut our losses by shortening all the poles to match the broken one. After a tense debate, the group decided to cut the poles and carry on building. There was a small consolation that all the poles were actually 12 meters long instead of 11. This meant that we didn't reduce the size of the structure as much as we initially feared.

    {{< img name="night_2.jpg" classes="right corners" alt="Description for screen readers." >}}
    Weaving nearly broke the team. Based on the prototypes, the team knew that weaving was the hardest part and took the most time. We had over-come more obstacles than anticipated just to get to this point. The team carried themselves well through roughly 18 hours of straight weaving. We even continued weaving through a dust storm.{{< break >}} Hoisting the structure was the last major hurdle. We were caught off guard with the realities of AfrikaBurn. After two and a half days of construction and weaving, we needed to stop and hold the structure in a precarious position overnight. There were risks involved in pausing construction but it provided a much needed rest. 

    The next morning, we got some unexpected assistance from the Clan cherry picker, which sped us along. We leaned the gateway into its final position and celebrated what we had done. But even though the structure was up, I still needed to finish setting up the lights.

    In the end, the photo-resistors, lasers and my beginner soldering skills didn't like the dust. After a couple of hours of failed trouble-shooting, I decided to abandon the interactive element of the lighting. Plan B was to create and cycle through a couple of predefined lighting effects.

    The end result was still impressive. We received a lot of great feedback from everyone who saw the gateway. It was rewarding to watch people's reactions as they walked through, running their fingers along the weave.

    My favorite thing to do was to walk through the gateway and try to touch my nose to the weave. Whenever I thought I was getting close, the threads would curve up and away from me. In hindsight, the smaller structure wasn't all bad. It made the gateway more relatable, more personal. The weave wasn't floating high above you, but was right there, in reach of your fingers. 

    Even though the project didn't go exactly as planned, I still consider it a success. There were many unexpected hurdles we had to overcome just to erect the gateway. But the whole exercise gave me an excuse to play with new technologies and concepts, and that was a win. 

*** Afrikaburn 2019: Ephemeropolis
    It is very hard to sum up my experiences and impressions. This post has focused on the Sweet Love Gateway but there was so... so very much more. I was invited to present & share my journey, so I created this [[https://slides.com/ultrachrisp/deck][slide deck]]. These slides only offer a taste of what was there.

    AfrikaBurn changed me for the better. It left me awed and humbled. The people, the projects, the setting... I still struggle to find words to adequately describe it.

    /Thank you AfrikaBurn, for everything you are!/

    {{< youtube L8V3rp6gvO8 >}}
