#+DATE: 2019-07-07T16:42:43+02:00
#+TITLE: Sweet Love Gateway
#+DRAFT: false
#+TYPE: post

{{< img name="night_1.jpg" classes="right corners" alt="Description for screen readers." >}}
Even though I got involved with the AfrikaBurn website build in 2010, Ephemeropolis was my first burn. Attending AfrikaBurn has long been on the to-do list, so we started making plans late last year. The core build team included [[https://www.facebook.com/igor.zeljko.77][Igor]], [[https://www.facebook.com/alastair.mehl][Alastair]], [[https://www.facebook.com/magoshashot][Margaret]], [[https://www.facebook.com/tiffanychi101][Tiffany]] & myself. There were more people involved with other projects built at Oppikoppi & Meilie-pop, but this was the team building at AfrikaBurn. AfrikaBurn is a better setting for art-projects, so contributing via building something seemed natural. <br><br> That something took the form of a gateway via a [[https://www.mathcurve.com/surfaces.gb/paraboloidhyperbolic/paraboloidhyperbolic.shtml][hyperbolic paraboloid]] (look at my fancy vocabulary). Igor, Alastair & Margaret had built this structure before but I thought there was room to refine 'how' it was build.
   
** Prototyping
   {{< img name="day_1.jpg" classes="left corners" alt="Description for screen readers." >}}
   This is one of those skills that matures like a fine wine. When I was young, brute force & enthusiasm would carry me through most projects. With time, I realised that I was making similar mistakes at similar stages of a project. Worse, the team made easily avoidable mistakes because they didn't check in with everyone who could add value to the project. The process of finding & fixing issues doesn't go away, it's 'when' you fix them that prototyping can help with. <br><br> Prototyping for pioneering projects was always a given. As a scout (aka young hot-shot who builds first & explains later, dealing with & fixing issues as they arise), prototyping was what the scout master told you to do which resulted in a small version of the real version. It was great for photo opportunities (small version in foreground, big version in background) but not much else (or so I thought). We did 'attempt' to measure the poles to scale, but more because we were told to.

   As I have mentioned in a [[https://chrispyke.com/post/almighty-prototype/][previous post]], prototypes are my sandbox. It's a space where I can play and make mistakes before the mistakes result in serious consequences. 

*** The Problem Statement
    The structure itself is simple enough. A square comprised of four square lashings at each corner. The hyperbolic paraboloid is created when you warp the 2D square into a 3D space. An interesting by-product of the shape is that the surface or mesh bends to accommodate the frame, but the individual threads or twines remain straight. Since the threads are straight, the problems to solve are:

    - How to secure the individual threads to the poles?
    - The optimal spacing between threads to create a dense enough surface to catch the LED light?
    - Possible ways to achieve the above without over working the build team?

    The first few times the structure was built, the spacing between threads was large. Too large to practically catch light. The threads where also tied to the poles individually, making the entire process labour intensive. Each thread needed to be tied into place individually. When the structure was hoisted into it's final position, each thread then need to be tightened. Unsurprisingly, Margaret did not have great things to say about this approach. It got the structure up, but it took a long time & a lot of effort. My programming self needed a way to speed this process up. There had to be a way to for-loop / while-loop / map over the threads.

*** Iteration
    I set about trying different approaches. The first prototype was concerned with the basic shape.
 
    - Could the hyperbolic paraboloid be hoisted into position from a flat 2D square? 
    - Would the shape appear if we had two flat, perpendicular surfaces that weren't woven into one another? 

    As much as a small scale prototype could, it did confirmed both questions. The structure would not be as secure as if the two planes were woven into one another, but the time spent weaving would be considerably reduced. It would also allow us to tighten threads without the thread getting caught in the weave. There were obvious problems with this prototype, but it served it's purpose & was super quick to make.

    The next problem was regarding the twine. Prototype 2 & 3 would be focused around solving the below:

    - How could we anchor the twine on the pole so that we could weave & tighten multiple threads at once?
    - Was there a possibility of weaving more than a single thread at a time?
    - Could we access the twine from the ground, once the structure was getting close to it's final shape?

    We started investigating different types of anchorage on the poles, weight the cost of the anchorage vs the number of anchors provided. One solution proposed by Igor or Tiffany (or both) was to use metal chains. If the chain was secured onto the pole, it provided a ton of anchorage points without having to individually secure each point (vs hooks or eye-hole bolts). It certainly wasn't a perfect solution, but it did provide the best 'number of anchor points per cost' ratio of the options explored.

    {{< img name="day_1.jpg" classes="right corners" alt="Description for screen readers." >}}
    The actual method of weaving the twine through the chains was the next major problem. Prototype 2 proved, after an afternoon of weaving, that simply feeding the twine through the chain was not good enough. The volume of thread, as well as possible confusion caused by different people weaving in slightly different ways, made this approach impractical. Igor suggested a different approach, feeding the incoming end of the twine through a single chain link, running the thread along the chain and then feed the out-going end through a chain link further down. This approach was much clearer as it was immediately evident which end of the twine needs to be pulled vs which end needs slack to take up the tension. Again, there is a programming term for this: clear & descriptive variable names.

    With these two pivotal issues solved in theory, I focused my attention on some of the finer construction issues. The surface area of the hyperbolic paraboloid is much smaller than a flat square. When building the structure, we can save a lot (but not all) of wasted twine by getting the starting shape as close to the final shape. This meant hoisting 2 corners up on barrels, as well as moving the base poles in. Additionally, if you are able to tighten the individual threads, you don't need access to all the anchor points, just half of them. So you could (in theory) keep one half of the structure on the ground & hoist the other half of the structure into the air. This could be done iteratively, and shouldn't need additional scaffolding to secure the part of the gate that is in the air.

    Armed with these insights from the prototypes, I felt confident that we could erect the structure on the day.

*** Individually Addressable Awesomeness
    I had an idea of 'how' I wanted to light the structure, but this was very new ground for me. It culminated into my first adventure into micro-controllers, and I was wholly unprepared for the end result.

    It started with crawling the internet, inspecting tutorials, looking at specs, looking at prices, re-looking at specs & prices, trying to factor redundancy into the system, just to start the process again when I found something more promising.

    The first problem to solve was power. After looking at what was available & what was most cost effective, we settled on a battery of car batteries (5 to be exact). There would be solar panels to charge them in the day, and they should provide more than enough power for the lights at night.

   {{< img name="night_3.jpg" classes="center corners" alt="Description for screen readers." >}}

    The reason for such a large power supply was the LED light strips, specifically the WS2813 (upgraded WS2812b) strips. We were able to source them at 5m / 60 LEDs per meter strips. Each strip at 300 individually addressable LEDs, with a potential power usage of 100w per strip (if each LED was burning at full brightness on white light). The structure was made of 4 x 11m poles, so we had roughly 40m that we needed to cover with LEDs. That is 2400 individually addressable LEDs... I was starting to get very excited.

    The LED strips ran of 5v, which was very handy. We needed step-down converters to get the 20v from the car-batteries to 5v to run the strips as well as the micro-controllers. I was able to get an idea of the processing power required to smoothly run that number of LED lights from [[https://github.com/FastLED/FastLED/issues/288][this thread]]. To ensure that I wasn't overworking the controllers, I decided to get an Arduino DUE for each pole.
 
    The next problem I wanted to solve was interaction. The theory was sound enough, and I got a working version up & running in my garage. I had 2 lasers that produced line beams and 6 photo-resistors to produce a 'trip wire' system. I then setup a Raspberry Pi 3b to receive signals from the photo-resistors & to then co-ordinate lighting effects with the Arduinos. As I worked on the system, I realised that I could simply the system by communicating over WIFI, rather than cabling. I then replaced the Arduino Duos with ESP32 controllers, and coordinated the communication between Pi & controller using the [[http://mqtt.org/][MQTT protocol]].    

    Time caught up with me in the end, so I did as many general tests as I could before packing up the system & preparing for the trip to Tankwa Town.

*** Role with it

    /"No plan survives first contact with the enemy,"/ said [[https://en.wikiquote.org/wiki/Helmuth_von_Moltke_the_Elder][Helmuth von Moltke the Elder]].

    {{< img name="day_2.jpg" classes="right corners" alt="Description for screen readers." >}}
    The group that I was traveling with had 2 full days of travel ahead of us (Johannesburg to Tankwa). We were venturing into the unknown (i.e. none of us had been to AfrikaBurn before), so there was some over preparation from our side. The first hurdle was separating the essential equipment from the 'nice to haves'. The second hurdle was to get everyone in the group into a car, and get the group moving. We were hit with a flat tire with one of the cars, and this was before we even left the good highways or started driving on gravel roads. All of these needed to be dealt with in turn, trying to balance the group feeling with the objectives.

    Once we got to Tankwa town & setup our tents, we went in search of our 11m poles. After much searching and entertaining of options, we were able to purchase the poles & have them transported to Tankwa via the clan's (the core AfrikaBurn group) processes. This greatly simplified our lives. We found the stacked poles by the clan structure, and decided to transport them to the build site & start building the following morning.

    The following morning, 3 of the 11m meter poles where gone. Everyone, including the organisers, were stunned. Search parties were sent out, calls were made and the whole camp started looking for the missing poles. They were eventually spotted by Igor at another project & the organsiser's helped transport them to the build site. The build team's moral took a hit.

    {{< img name="night_2.jpg" classes="left corners" alt="Description for screen readers." >}}
    We started securing the chains to the poles when one of the poles snapped. There were many possible reasons why (left out in the desert for too long, rough treatment by the pole thieves, the wood was untreated by choice) but that didn't solve the problem. Two main options appeard: try to fix/ brace the broken pole with metal (causing further delays); Literally cutting our losses by shortening all the poles to match the broken one. There was debate, but the group decided to cut the poles and carry on building. There was a small consolation that all the poles were actually 12m long instead of 11m, so the structure wasn't as small as we initially feared. Moral took another hit.

    Weaving nearly broke the team. Based on the prototypes, the team knew that weaving was the hardest part & took the most time. We had over-come more obstacles than anticipated just to get to this point. I am impressed of how the team carried themselves through the roughly 18 hours of straight weaving, even through a dust storm. But the seeds for the team's demise were planted at this point.

    Hoisting the structure was the last hurdle for the core build team. We were caught off guard with the realities of AfrikaBurn. After 2 & a half days of construction & weaving, we needed to stop & hold the structure in a precarious position overnight. This slammed moral even further, but it was a much needed rest. We got some unexpected assistance from the clan cherry picker then next day, which helped us with the final stage of the project. We leaned the gateway into its final position & celebrated what we had done. But even though the structure was up, I still needed to finish setting up the lights.

    In the end, the photo-resistors, lasers as well as my beginner welding skills did not like the dust. After a couple of hours of failed trouble-shooting, I decided to abandon the interaction part of the lighting & just cycle the lights through a couple of effects. The end result was still impressive & we recieved a lot of great feedback from everyone who saw the gateway.
*** Afrikaburn 2019: Ephemeropolis

    It is very hard for me to 
    {{< youtube L8V3rp6gvO8 >}}
